### ISSUE TITLE
google form link accessibility 

### ISSUE THREAD

**Issue by rs1dev** [ossd-s23/KodeHub#7]
Hey guys! When I tried accessing the google form linked in the contributing.md file with my github email address which is non-nyu it gave me this message: 
<img width="643" alt="Screenshot 2023-02-27 at 4 48 26 AM" src="https://user-images.githubusercontent.com/123398993/221530323-b4622500-8d31-4610-81a6-de89b902e859.png">
When I clicked the [Learn More](https://support.google.com/docs/answer/160166?visit_id=638130871122427038-3170656528&p=forms_settings&rd=1) link, I found this this info - "When someone makes a form through work or school, only people in their organization can see the form. Unless they change that setting, these forms can’t be viewed from a Gmail account." 
Detailed instructions to change this restriction are in the same link, but I believe the steps are Settings -> Responses -> Uncheck the box: Restrict to users in [nyu.edu] and its trusted organizations. This should fix it, but if it doesn't let me know and I can try looking into it further. It's totally up to you all if you want to allow contributors outside NYU, but just thought I'd let you know about this since we're striving for FOSS :)

**Comment by estelacruz** [comment]
Thank you so much for bringing this issue to our attention, we have updated the Feedback form and taken away any restrictions. We appreciate your collaboration!
