### ISSUE TITLE
.Rhistory file inquiry 

### ISSUE THREAD

**Issue by rs1dev** [ossd-s23/KodeHub#8]
In the KodeHub repository, there is a [.Rhistory](https://github.com/ossd-s23/KodeHub/blob/main/.Rhistory) file. I was wondering what the purpose of this file is and if it is needed since it is currently empty...

**Comment by estelacruz** [comment]
Essentially, R generates a .Rhistory file which contains a log of commands that have been executed in the R console. Generally, this file is not necessary for collaborating on projects, as it is specific to an individual's R console. Thank you for pointing this out and bringing it to our attention!
